apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: nekropolis
  name: nekropolis-workers
spec:
  clusterName: nekropolis
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: nekropolis
      cluster.x-k8s.io/deployment-name: nekropolis-workers
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: nekropolis
        cluster.x-k8s.io/deployment-name: nekropolis-workers
        node-role.kubernetes.io/node: ''
    spec:
      # amount of seconds a machine has to be ready until it is considered available
      minReadySeconds: 10
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: nekropolis-worker
      clusterName: nekropolis
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: ProxmoxMachineTemplate
        # the german numeral suffix at the end is used to differentiate machine templates
        # within the same kubernetes release, since they should not be modified
        # see https://cluster-api.sigs.k8s.io/tasks/updating-machine-templates.html
        name: nekropolis-worker-1.33.7-eins
      version: v1.33.7
