apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

helmCharts:
  # https://github.com/openbao/openbao-helm
  # https://github.com/openbao/openbao-helm/tree/main/charts/openbao
  - name: openbao
    repo: https://openbao.github.io/openbao-helm
    version: "0.25.6"
    releaseName: openbao
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - cnpg-openbao.yaml
  - gateway-api.yaml
patches:
  - path: patch-delete-helm-test-pod.yaml
