apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

# https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
helmcharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    # defining the namespace here is necessary because of the namespace being used in
    # the container arguments of the deployments
    # see https://github.com/external-secrets/external-secrets/issues/2273
    namespace: external-secrets
    version: 0.20.2
    releaseName: external-secrets
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - clustersecretstore.yaml
