
# https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.19.3
    releaseName: certmanager-release
    namespace: cert-manager
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - clusterissuer.yaml
