apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: metrics-server
    server: "https://kubernetes.default.svc"
  project: unterbau
  source:
    path: manifests/metrics-server
    repoURL: "https://github.com/AtomSoldat/private-cloud.git"
    targetRevision: master
