apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs
  #this finaliser causes cascading deletion (delete children)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: csi-nfs
    server: "https://kubernetes.default.svc"
  project: unterbau
  source:
    path: manifests/csi-nfs
    repoURL: "https://github.com/MausoleumManagement/storage.git"
    targetRevision: master
