apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - application-argocd.yaml
  - application-cert-manager.yaml
  - application-cilium.yaml
  - application-cluster-api.yaml
  - application-cnpg.yaml
  - application-csi-nfs.yaml
  - application-external-secrets.yaml
  - application-hardcoredns.yaml
  - application-kube-vip-cloud-controller.yaml
  - application-openbao.yaml
