# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/_helpers.tpl
global:
  domain: argocd.irminsul

configs:
  gpg:
    keys:
      FD9D433219DA6540: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        
        mDMEaNG8nxYJKwYBBAHaRw8BAQdAyZYzGFeocprW5rrlw0wKi5/Tnr+qX1PSm4Aw
        xZUL71+0Ikxlb24gV2VsY2hlcnQgPGxpY2h0dXJtQHBvc3Rlby5kZT6IlgQTFgoA
        PhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byfAhsDBQkFo5qABQsJCAcCBhUK
        CQgLAgQWAgMBAh4BAheAAAoJEP2dQzIZ2mVAjTQA+wVV7UESwF+HQ2bddio2+EMM
        rB9kJtgymXT5Rrah51dsAPwI1kJYJbbhg+4e0Zi7PpqjYImd3bb4EPYH77u/BOyP
        B7g4BGjRvJ8SCisGAQQBl1UBBQEBB0A2S2JfMY5AFFOMxj7n4TvBk1kADxGtQTTS
        60pESu85JQMBCAeIfgQYFgoAJhYhBCLDFqNT9vEe0mk2KP2dQzIZ2mVABQJo0byf
        AhsMBQkFo5qAAAoJEP2dQzIZ2mVAcewA/0wM4Gfgi1ePoNwksvf2G2tCu9L8U+0H
        M/OZP0vjJ/UoAQCHgcMYzsJndTx/+a9HAIX/bv2nfPWtZGB6jaZmqtzgCA==
        =53+B
        -----END PGP PUBLIC KEY BLOCK-----
externalRedis:
  host: valkey
  port: 6379
  existingSecret: argocd-valkey

server:
  service:
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.13.3
    type: LoadBalancer

redis:
  enabled: false
notifications:
  enabled: false

