apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubelet-serving-cert-approver
resources:
- https://github.com/alex1989hu/kubelet-serving-cert-approver//deploy/standalone?timeout=120&ref=v0.10.2
# the kustomization comes with its own namespace manifest
#- namespace.yaml
