apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

resources:
  # https://github.com/stakater/Reloader
  - https://github.com/stakater/Reloader//deployments/kubernetes?ref=v1.0.118
  - namespace.yaml

