# https://github.com/CloudPirates-io/helm-charts
# Standalone valkey instance used as harbor's external redis replacement

architecture: standalone

auth:
  enabled: true
  existingSecret: harbor-valkey
  existingSecretPasswordKey: REGISTRY_REDIS_PASSWORD

persistence:
  storageClass: cephfs-2026
  size: 8Gi
