apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: hello-world
    server: https://kubernetes.default.svc
  project: tand-nippes-kinkerlitzchen-elaborat
  source:
    path: manifests/hello-world
    repoURL: https://github.com/Atomsoldat/demo_k8s_application.git
    targetRevision: master
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
